### PR TITLE
Fix empty geometry in case of immediate attribute window pop-up

### PR DESCRIPTION
**Pull request by mclucky**
Hi @elpaso 

This is a quick fix for #20 and worked for us.

### CODE REVIEW

**Comment by mclucky** [comment]
Hi @elpaso 

Any comments from your side?

**Comment by elpaso** [comment]
This plug-in functionality is now in QGIS 3 core and 2.18 is end of life, I'm not going to update this plug-in any more. Let me know if you want to take over as maintainer.

**Comment by mclucky** [comment]
@elpaso thanks for your reply. Let me think about it - talk to you soon.

**Comment by mclucky** [comment]
Hi @elpaso 

Pls give me write access to merge the pull request.
I can't guarantee maintenance cause in the meantime we migrated to QGIS 3, but let's see we still have some cases related to qgis2.

**Pull request merged**
